### ISSUE TITLE
git LWRP never times out on failure

### ISSUE THREAD

**Issue by signe** [chef-cookbooks/git#65] opened 2015-06-15 20:33 UTC
Attempting to sync a repository with an incorrect or missing SSH key causes the git LWRP to hang until manually killed:

```
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/[...]/recipes/git.rb:23:in `from_file'

    git("/usr/local/bin") do
      action [:sync]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      destination "/usr/local/bin"
      enable_checkout true
      revision "HEAD"
      remote "origin"
      checkout_branch "master"
      declared_type :git
      cookbook_name "[...]"
      recipe_name "git"
      repository "git@github.com:[...].git"
    end
```

The attempt failed after a manual ^C, after 548s.

**Comment by signe** [comment] 2015-06-18 00:06
This was identified to be a missing host key for github.com, however this still seems like a failure case that needs to be handled, by automatically rejecting unknown keys instead of waiting for git/ssh to time out, which it will never do.

**Comment by johnbellone** [comment] 2015-06-18 01:19
This is definitely something that should timeout.

**Comment by darrin** [comment] 2015-07-10 01:49
I just ran into this. I can confirm that I had an empty deploy key (not a missing host key)  referenced by my gitwrapper... after populating that I was able to proceed.

**Comment by someara** [comment] 2015-07-20 17:12
I believe this is an issue with the git resource shipped in Chef core

https://docs.chef.io/resource_git.html

Can you file this over here? https://github.com/chef/chef/issues

**Comment by iennae** [comment] 2016-01-29 00:15
Based on https://docs.chef.io/resource_git.html it looks like there is a parameter timeout. I am closing this issue as this parameter does exist but doesn't look like it's in use. Feel free to reopen if you find that this doesn't solve your problem.

**Closed by iennae** 2016-01-29 00:15 UTC
Labels: bug, invalid
